<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $branch_id_1 = 1;
        $branch_id_2 = 2;
        $branch_id_3 = 3;
        $branch_id_4 = 4;
        $branch_id_5 = 5;
        $branch_id_6 = 6;
        $branch_id_7 = 7;
        $branch_id_8 = 8;
        $branch_id_9 = 9;

        $users = [
            //chi nhanh 1
    		[
	            'full_name' => 'Super Admin',
	            'email' => 'admin@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_admin'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654321',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_male'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Ngô Thu Phương',
	            'email' => 'phuongnt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654322',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Đức Chung',
	            'email' => 'chungnd@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654323',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_male'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => '1573049781beauticians03.jpg'
            ],
    		[
	            'full_name' => 'Đào Uyên',
	            'email' => 'uyendt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654324',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => '1573049602beauticians01.jpg'
            ],
    		[
	            'full_name' => 'Nguyễn Nhật Hảo',
	            'email' => 'haonn@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654325',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => '1573049757beauticians02.jpg'
            ],
            [
	            'full_name' => 'Nguyễn Thị Bích Ngọc',
	            'email' => 'ngocntb@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654326',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => '1573049886beauticians04.jpg'
            ],
    		[
	            'full_name' => 'Nguyễn Phương Anh',
	            'email' => 'anhnp@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654327',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Bùi Thị Ánh',
	            'email' => 'anhbt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654328',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_1,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            //chi nhanh 2
            [
	            'full_name' => 'Ngô Thu Hẳng',
	            'email' => 'hangnt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654331',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Khánh Linh',
	            'email' => 'linhnk@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654332',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thu Trang',
	            'email' => 'trangnt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654333',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thu Hà',
	            'email' => 'hant93@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654334',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Ngọc Bích',
	            'email' => 'bichnn97@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654335',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Phương Hà',
	            'email' => 'hanp999@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654336',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Bùi Thị Xuân',
	            'email' => 'xuanbt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654337',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_2,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            //chi nhanh 3
            [
	            'full_name' => 'Đoàn Thùy Linh',
	            'email' => 'linhdt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654341',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thu Thủy',
	            'email' => 'thuynt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654342',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thu Hảo',
	            'email' => 'haont@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654343',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thanh Huyển',
	            'email' => 'huyennt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654344',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Ngọc Ánh',
	            'email' => 'anhnn96@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654345',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Phương Linh',
	            'email' => 'linhnp@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654346',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thị Thảo',
	            'email' => 'thaont@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654347',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_3,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            //chi nhanh 4
            [
	            'full_name' => 'Nguyễn Hồng Vân',
	            'email' => 'vannh@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654351',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Khánh Thi',
	            'email' => 'think@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654352',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Vân Trang',
	            'email' => 'trangnv@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654353',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thị Hương',
	            'email' => 'huongnt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654354',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Thị Hoa',
	            'email' => 'hoant@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654355',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Lan Anh',
	            'email' => 'anhnl@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654356',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Ánh Nguyệt',
	            'email' => 'nguyetna@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654357',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_4,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            //chi nhanh 5
            [
	            'full_name' => 'Đoàn Thùy Trang',
	            'email' => 'trangdt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654361',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thảo Vân',
	            'email' => 'vannt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654362',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Bảo Vy',
	            'email' => 'vynb@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654363',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Gia Hân',
	            'email' => 'hanng@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654364',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Hoài An',
	            'email' => 'annh@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654365',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Khánh Ngân',
	            'email' => 'ngannk@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654366',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Khánh Chi',
	            'email' => 'chink@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654367',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_5,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            // chi nhanh 6
            [
	            'full_name' => 'Ngô Thu Hà',
	            'email' => 'hant@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654371',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thanh Hà',
	            'email' => 'hant2@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654372',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Bích Thảo',
	            'email' => 'thaonb@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654373',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Bích Thủy',
	            'email' => 'thuynb@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654374',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Hiền Thục',
	            'email' => 'thucnh@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654375',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Minh Tâm',
	            'email' => 'tamnm@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654376',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Bùi Mỹ Tâm',
	            'email' => 'tambm@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654377',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_6,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            // chi nhanh 7
            [
	            'full_name' => 'Nguyễn Phương Trinh',
	            'email' => 'trinhnp@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654381',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Phương Thảo',
	            'email' => 'thaonp@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654382',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thảo Chi',
	            'email' => 'chint@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654383',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Hương Chi',
	            'email' => 'chinh@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654384',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Bảo Quyên',
	            'email' => 'quennb@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654385',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Diễm Châu',
	            'email' => 'chaund@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654386',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Bùi Gia Mỹ',
	            'email' => 'mybg@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654387',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_7,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            // chi nhanh 8
            [
	            'full_name' => 'Ngô Hồng Nhung',
	            'email' => 'nhungnh@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654391',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Kim Oanh',
	            'email' => 'oanhnk@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654392',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Mỹ Duyên',
	            'email' => 'duyennm@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654393',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Kim Liên',
	            'email' => 'liennk@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654394',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Ngọc Diệp',
	            'email' => 'diepnn@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654395',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Ngọc Hà',
	            'email' => 'hann@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654396',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Bùi Ngọc Hoa',
	            'email' => 'hoann@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654397',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_8,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
            // chi nhanh 9
            [
	            'full_name' => 'Ngô Thanh Trúc',
	            'email' => 'trucnt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_manager'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654301',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thanh Vân',
	            'email' => 'vannt3@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654302',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Thu Nguyệt',
	            'email' => 'nguyetnt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654303',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Tuyết Vy',
	            'email' => 'vynt96@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654304',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
            [
	            'full_name' => 'Nguyễn Gia Bảo',
	            'email' => 'baong@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_technician'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654305',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_display'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Nguyễn Ngọc Lan',
	            'email' => 'lannn@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_cashier'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654306',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],
    		[
	            'full_name' => 'Bùi Thiên Kim',
	            'email' => 'kimbt@localhost.com',
	            'password' => bcrypt('12345678'),
                'role_id'   => config('contants.role_receptionist'),
                'birthday'  =>  '1990-10-25',
                'phone_number'  => '0987654307',
                'address'   =>  '216 Cầu Giấy',
                'branch_id' => $branch_id_9,
                'gender_id' => config('contants.gender_female'),
                'operation_status_id' => config('contants.operation_status_active'),
                'display_status_id' => config('contants.display_status_hide'),
                'avatar' => 'avatar-default.png'
            ],

    	];
        DB::table('users')->insert($users);
    }
}
