<?php
return [
    'role_admin'                    => 1,
    'role_manager'                  => 2,
    'role_technician'               => 3,
    'role_cashier'                  => 4,
    'role_receptionist'             => 5,
    'bill_status_paid'              => 2,
    'bill_status_unpaid'            => 1,
    'display_status_display'        => 2,
    'display_status_hide'           => 1,
    'gender_male'                   => 1,
    'gender_female'                 => 2,
    'gender_other'                  => 3,
    'operation_status_active'       => 1,
    'operation_status_inactive'     => 2,
    'order_status_unconfimred'      => 1,
    'order_status_confimred'        => 2,
    'order_status_handling'         => 3,
    'order_status_finish'           => 4,
    'location_display_left'         => 1,
    'location_display_right'        => 2,
    'upload_photo_library_path'     => 'upload/images/photo_library/',
    'img_default_4_3'               => 'img-default.png',
    'route_update_photo'            => 'admin/photo-library/update/',
    'route_destroy_photo'           => 'admin/photo-library/destroy/',
    'take_load_take_photo'          => 12
];
